baseURL = 'https://aleos.dev/'
languageCode = "en"
defaultContentLanguage = "en"
title = 'aleos'
theme = 'hugo-coder'

[params]
author = "Alexander Ostrovsky"
description = "Alexander Ostrovsky's personal website"
keywords = "blog,developer,personal"
info = ["iOS Developer"]
avatarURL = "images/avatar.png"
dateFormat = "2 Jan 2006"
since = 2011
colorScheme = "auto"
customCSS = ["css/custom.css"]

# Markup configuration
# [markup.highlight]
# style = "xcode-dark"

# Social links
[[params.social]]
name = "GitHub"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/aleos/"

[[params.social]]
name = "Twitter"
icon = "fa-brands fa-x-twitter fa-2x"
weight = 3
url = "https://twitter.com/aleos/"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 4
url = "https://www.linkedin.com/in/thealeos/"

# Language configuration
[languages]
[languages.en]
disabled = false
[languages.ru]
disabled = true

# Menu links
[[menu.main]]
name = "Blog"
weight = 1
url = "posts/"
[[menu.main]]
name = "About"
weight = 2
url = "about/"
