baseURL = 'https://aleos.dev/'
languageCode = 'en-us'
title = 'aleos'
theme = 'hugo-coder'

[params]
author = "Alexander Ostrovsky"
# license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "Alexander Ostrovsky's personal website"
keywords = "blog,developer,personal"
info = ["iOS Developer"]
# avatarURL = "images/avatar.jpg"
gravatar = "thealeos@gmail.com"
# dateFormat = "January 2, 2006"
since = 2019
# Git Commit in Footer, uncomment the line below to enable it
# commit = "https://github.com/luizdepra/hugo-coder/tree/"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
colorScheme = "auto"

[markup.highlight]
# style = "xcode-dark"

# [taxonomies]
# category = "categories"
# series = "series"
# tag = "tags"
# author = "authors"

[[params.social]]
name = "GitHub"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/aleos/"

[[params.social]]
name = "Twitter"
icon = "fa-brands fa-x-twitter fa-2x"
weight = 3
url = "https://twitter.com/aleos/"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 4
url = "https://www.linkedin.com/in/thealeos/"

# Menu links
[[menu.main]]
name = "Blog"
weight = 1
url = "posts/"
[[menu.main]]
name = "About"
weight = 2
url = "about/"
